### ISSUE TITLE
ERROR: QA Issue compiling gnuradio-dev-image

### ISSUE THREAD

**Issue by belza** [balister/meta-sdr#21]
Hi Balister, I have followed the steps of the page https://github.com/Nuand/bladeRF/wiki/Creating-Linux-based-Embedded-System-Images-with-Yocto and I compiled  successfully the the core-image-minimal that works properly. However, when I try to compile the gnuradio-dev-image I found the following errors:

ERROR: QA Issue: File '/usr/lib/libqwtmathml.so.6.0.1' from qwt was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/usr/lib/libqwt.so.6.0.1' from qwt was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/usr/lib/qt4/plugins/designer/libqwt_designer_plugin.so' from qwt was already stripped, this will prevent future debugging! [already-stripped]

Please, can you provide any help ?

Best regards, Pablo Belzarena

**Comment by balister** [comment]
It feels like the QA message was switched form a warning to an error and
back recently. I'll need to do some digging.

I should really fix the unerlying issue, but that won't help right away.

Philip

**Comment by jynik** [comment]
@belza, 

I have updated the wiki page you were using to:
 * Use the latest Yocto release (Jethro)
 * Provide a [workaround](https://github.com/Nuand/bladeRF/wiki/Creating-Linux-based-Embedded-System-Images-with-Yocto) for the issue you're encountering.

**Comment by belza** [comment]
Thank you very much for your help. With the new version of Yocto and adding 
INSANE_SKIP_qwt_append = "already-stripped" in the local.conf I can compile the gnuradio-dev-image.

However, when I try to compile the gnuradio-demo-image I found some errors like the following:

ERROR: Multiple .bb files are due to be built which each provide virtual/libgl (/home/belza/Yocto/poky-jethro-2.0/meta/recipes-graphics/mesa/mesa_10.6.3.bb /home/belza/Yocto/poky-jethro-2.0/meta/recipes-graphics/mesa/mesa-gl_10.6.3.bb

Please, can you provide any help ?

Best regards, Pablo Belzarena.

**Comment by balister** [comment]
You need a PREFERRED PROVIDER line. Askin gthe #oe on freenode wil get
you a bigger audience for general questions.

**Comment by belza** [comment]
Thank you very much. I will follow your suggestions.

**Comment by balister** [comment]
Sorry for the trouble, I'm caught up in some other stuff right now :(

**Comment by balister** [comment]
There is an active pull request that should resolve these issues. Closing
