### ISSUE TITLE
Can you add the recipe for PyQwt?

### ISSUE THREAD

**Issue by DengkeDu** [balister/meta-sdr#29]
Hi balister, Can you add the recipe for PyQwt? Or gnuradio program could not contain the wiget, such as slider.

**Comment by trondeau** [comment]
PyQWT is no longer needed for GNU Radio widgets, like the QTGUI Range (which is a slider). We use QWT in C++ and swig everything into Python.

PyQWT is no longer a supporter project and does not work with QWT6.

**Comment by balister** [comment]
Thanks Tom. I was hunting for the email and couldn't find it.

Philip

**Comment by DengkeDu** [comment]
Hi Tom, when I drag the QTGUI Range into my flowgraph, it produced a python file that contain `import PyQt4.Qwt5 as Qwt`, I have `bitbake gnuradio` successfully. But on my target(beaglelbone black), I can't find the module under the path `/usr/lib/python2.7/site-packages/PyQt4`.

**Comment by DengkeDu** [comment]
OK, thanks Tom! I want to make a simple program show the radio frequency on beaglebone black, which need a slider to control the frequency, how can I do it? I have `bitbake core-image-sato` that contain `gnuradio rtl-sdr` successfully.
