### ISSUE TITLE
where are the dev packages (looking for headers)

### ISSUE THREAD

**Issue by tjenssen** [balister/meta-sdr#38]
I am very new with yocto but have some experience with Qt running on a prepared image. I miss the headers from the image, or a SDK build where I have a cross-compiled environment.
Is it me or is this missing?

**Comment by remleduff** [comment]
The dev packages are automatically created and named something like "libgnuradio-blocks-dev".

The gnuradio-dev package is supposed to add all of them if you add it, but there is currently a bug where it doesn't, so you have to add them individually.

**Comment by balister** [comment]
Closing, this should work.
