### ISSUE TITLE
Petalinux Fails to Build 

### ISSUE THREAD

**Issue by sanjuambiger** [balister/meta-sdr#53]
Hi ,
i am building image for ZC706 board  using Petalinux 2018.3 . i followed this link for adding meta-sdr user layer for GNU Radio.
[https://github.com/phase4ground/DVB-receiver/wiki/Adding-gnuradio-to-the-Petalinux-2018.2-BSP-based-build-for-the-Ultra96-board](url)

but build is failing due to following Error 

**ERROR: gnuradio-3.8.0+gitAUTOINC+d78f7fcd0d-r0 do_fetch: Fetcher failure: Unable to find revision d78f7fcd0dadd362fcdc99194da5343a506eb519 in branch next even from upstream
ERROR: gnuradio-3.8.0+gitAUTOINC+d78f7fcd0d-r0 do_fetch: Fetcher failure for URL: 'git://github.com/gnuradio/gnuradio.git;branch=next;protocol=https'. Unable to fetch URL from any source.
ERROR: gnuradio-3.8.0+gitAUTOINC+d78f7fcd0d-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/bel/WorkSpace/analog/build/tmp/work/cortexa9hf-neon-xilinx-linux-gnueabi/gnuradio/3.8.0+gitAUTOINC+d78f7fcd0d-r0/temp/log.do_fetch.24235
ERROR: Task (/home/bel/WorkSpace/meta-sdr-rocko-gr-next/recipes-core/gnuradio/gnuradio_git.bb:do_fetch) failed with exit code '1'**

i am using rocko-gr-next branch of meta-sdr.
Can anyone  help me to fix this issue ?
Thanks in advance

**Comment by balister** [comment]
Rocko is pretty dated at this point. Try updating the branch and SRCREV the fetcher is looking for. I'd try and move it to the the tag for 3.8.2.0

**Comment by sanjuambiger** [comment]
Hi @balister Thank u for the reply , 
i am using petalinux 2018.3 , i had to use rocko branch only .
how would get SRCREV the fetcher for gnuradio 3.8.2.0 ?

**Comment by balister** [comment]
Use git to work out the rev you need. I am closing this since I do not have time to support rocko.
