### ISSUE TITLE
Dunfell Branch:   The unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by tflorkowski** [balister/meta-sdr#57]
Hi,

the recipes in the Dunfell branch use the unauthenticated git protocol that is no longer supported.
Could you push the commit that fixes the issue in master to Dunfell?

Best regards,

Thomas

**Comment by balister** [comment]
I merged a pull request that may have fixed this. Can you check and reply so I can close this?

**Comment by tflorkowski** [comment]
Works great. Thanks.
