### ISSUE TITLE
gr-mac recipe broken

### ISSUE THREAD

**Issue by jpendlum** [balister/meta-sdr#63]
It looks like John Malsbury's github account has disappeared along with gr-mac.

https://github.com/balister/meta-sdr/blob/139b41c45a1145fdf7323e2aa1408c434fe058b6/recipes-support/gr-mac/gr-mac_git.bb#L2

**Comment by balister** [comment]
CLosed by a recent PR deleting the recipe. Thanks for pointing this out!
